"""
Photo School curriculum data — 15 principles x 11 genres.

Extracted from app.py (Session 95) for maintainability: this is pure data,
edited far more often than app.py's logic, and keeping it inline made every
content-only change a diff against a 19,000+ line file. No behavior change —
_CURRICULUM and _CURRICULUM_BY_ID are identical in shape and content to what
was previously defined inline in app.py.

Each entry: (principle_id, dimension, depth, title, principle,
             commons_file, commons_caption, master, master_quote,
             assignments dict keyed by genre)
"""

_CURRICULUM = [
    # ── DoD ──────────────────────────────────────────────────────────────
    {
        'id': 'D1.1', 'dim': 'dod', 'depth': 1,
        'title': 'The Cost of the Decision',
        'principle': 'Difficulty is not complexity. It is the cost of the decision.',
        'commons_file': None,
        'commons_caption': None,
        'master': None, 'master_quote': None,
        'assignments': {
            'Wildlife':     'Name the one thing that made this shot hard to get. Not the gear — the decision. Where you had to be, how long you had to wait, what you gave up to be in that position. If you cannot name it, the frame did not cost you enough.',
            'Street':       'Find the frame that required you to step into the scene, not observe it from outside.',
            'Nature':       'Shoot in a condition you would normally avoid — rain, wind, flat noon light.',
            'Landscape':    'Get somewhere before the light arrives. The difficulty is the journey.',
            'People':       'Ask someone you do not know if you can photograph them. The ask is the difficulty.',
            'Documentary':  'Get inside the frame rather than recording it from a safe distance.',
            'Macro':        'Shoot at your maximum magnification in available light. No tripod.',
            'Creative':     'Choose a technique you have not mastered. The lack of control is the point.',
            'Drone':        'Fly in a condition you would normally cancel for. Wind teaches more than calm.',
            'Wedding':      'Shoot the ceremony without flash. The restriction is the difficulty.',
            'Fashion':      'Take the shoot outside. Remove the controlled environment entirely.',

            'Wildlife_mobile':      'Get to a location before first light and stay until thirty minutes after sunrise. The assignment is proximity: get closer to your subject than you have before. Without a telephoto, your DoD is in how close you physically got. Note in your submission how close you were.',
            'Street_mobile':      "Photograph in the most challenging light you can find today — direct midday sun, deep shade with a bright background, a lit interior against a dark exterior. The phone's sensor makes this hard. Work with it: expose for the subject, let everything else go where it goes. One frame. No editing.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      'Photograph in weather. Rain, heavy cloud, fog, harsh wind — the conditions that make most photographers stay home. The phone is weather-resistant enough. Protect it, go out, photograph in the difficulty. The image should show what the conditions were.',
            'People_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Documentary_mobile':      "Go somewhere you have never photographed before. Not exotic — unknown. A part of your city you don't know, a neighbourhood you've driven past, a community you're not part of. Spend one hour. Photograph what you find. The assignment is access: go somewhere a camera would close doors.",
            'Macro_mobile':      "Find the smallest subject you can photograph sharply on your phone. An insect, a flower stamen, a water droplet, a grain of sand. To fill the frame you must get as close as your phone's minimum focus distance allows. Find that distance, lock focus manually if your phone supports it, and hold still. The DoD is in the patience and proximity.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Find the hardest shot you can make at home — low light, moving subject, no extra gear.',
    },
    {
        'id': 'D1.2', 'dim': 'dod', 'depth': 2,
        'title': 'The Harder Position',
        'principle': 'The harder position always exists. Most photographers do not take it.',
        'commons_file': 'File:Ansel_Adams_and_camera.jpg',
        'commons_caption': 'Ansel Adams with his camera, c. 1950 · Public domain',
        'master': 'Ansel Adams', 'master_quote': 'Twelve significant photographs in any one year is a good crop.',
        'assignments': {
            'Wildlife':     'Find the angle that takes real patience to reach safely — get to eye level, stay downwind, wait in cover. The effort is the difficulty, never the distance to the animal.',
            'Street':       'Step into the scene you are photographing.',
            'Nature':       'Find the position you did not take last time because it was uncomfortable. Take it.',
            'Landscape':    'Shoot from a position that required physical effort to reach.',
            'People':       'Move twice as close as feels comfortable.',
            'Documentary':  'Stand where the story is happening, not where it can be safely observed.',
            'Macro':        'Shoot from underneath, behind, or through the subject.',
            'Creative':     'Build a setup with one element you cannot fully predict.',
            'Drone':        'Fly lower than you normally would. Proximity is the difficulty.',
            'Wedding':      'Get between the couple and the crowd. Not behind the crowd.',
            'Fashion':      'Choose a location with no shelter, no comfort, no control.',

            'Wildlife_mobile':      'Get to a location before first light and stay until thirty minutes after sunrise. The assignment is proximity: get closer to your subject than you have before. Without a telephoto, your DoD is in how close you physically got. Note in your submission how close you were.',
            'Street_mobile':      "Photograph in the most challenging light you can find today — direct midday sun, deep shade with a bright background, a lit interior against a dark exterior. The phone's sensor makes this hard. Work with it: expose for the subject, let everything else go where it goes. One frame. No editing.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      'Photograph in weather. Rain, heavy cloud, fog, harsh wind — the conditions that make most photographers stay home. The phone is weather-resistant enough. Protect it, go out, photograph in the difficulty. The image should show what the conditions were.',
            'People_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Documentary_mobile':      "Go somewhere you have never photographed before. Not exotic — unknown. A part of your city you don't know, a neighbourhood you've driven past, a community you're not part of. Spend one hour. Photograph what you find. The assignment is access: go somewhere a camera would close doors.",
            'Macro_mobile':      "Find the smallest subject you can photograph sharply on your phone. An insect, a flower stamen, a water droplet, a grain of sand. To fill the frame you must get as close as your phone's minimum focus distance allows. Find that distance, lock focus manually if your phone supports it, and hold still. The DoD is in the patience and proximity.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Find the hardest angle in your room. Go lower, closer, or into the light.',
    },
    {
        'id': 'D1.3', 'dim': 'dod', 'depth': 3,
        'title': 'When the Cost Disappears, Raise It',
        'principle': 'When the cost disappears, raise it deliberately.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Michael Kenna', 'master_quote': 'I wait for the light to speak to me.',
        'assignments': {
            'Wildlife':     'No vehicle, no hide — stay in one position using only natural cover for at least 30 minutes. Patience is now the entire challenge.',
            'Street':       'Tape over the LCD. Shoot blind for one hour. Trust your reading of the scene.',
            'Nature':       'One frame only per subject. No review, no reshoot.',
            'Landscape':    'Shoot moving water twice — once at 1/1000 to freeze every droplet, once at 2 seconds to turn it silky. Decide which version tells the truth about the place.',
            'People':       'Available light only. No reflector. No assistant.',
            'Documentary':  'No wide angle. Everything at 50mm or longer. Force yourself into proximity.',
            'Macro':        'Handheld. Moving subject. Maximum magnification.',
            'Creative':     'Set a slow shutter speed (1/15 to 1/4 second) and zoom your lens from wide to tight — or tight to wide — during the exposure. The subject becomes streaks of light and colour moving toward or away from you. Shoot ten frames and find the one where the movement feels intentional.',
            'Drone':        'Manual mode only. No automated flight path.',
            'Wedding':      'Document the day entirely as an observer. No directing, no posing.',
            'Fashion':      'One light source only — whatever exists in the location.',

            'Wildlife_mobile':      'Get to a location before first light and stay until thirty minutes after sunrise. The assignment is proximity: get closer to your subject than you have before. Without a telephoto, your DoD is in how close you physically got. Note in your submission how close you were.',
            'Street_mobile':      "Photograph in the most challenging light you can find today — direct midday sun, deep shade with a bright background, a lit interior against a dark exterior. The phone's sensor makes this hard. Work with it: expose for the subject, let everything else go where it goes. One frame. No editing.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      'Photograph in weather. Rain, heavy cloud, fog, harsh wind — the conditions that make most photographers stay home. The phone is weather-resistant enough. Protect it, go out, photograph in the difficulty. The image should show what the conditions were.',
            'People_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Documentary_mobile':      "Go somewhere you have never photographed before. Not exotic — unknown. A part of your city you don't know, a neighbourhood you've driven past, a community you're not part of. Spend one hour. Photograph what you find. The assignment is access: go somewhere a camera would close doors.",
            'Macro_mobile':      "Find the smallest subject you can photograph sharply on your phone. An insect, a flower stamen, a water droplet, a grain of sand. To fill the frame you must get as close as your phone's minimum focus distance allows. Find that distance, lock focus manually if your phone supports it, and hold still. The DoD is in the patience and proximity.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Impose one real constraint: shoot everything today with your phone only.',
    },
    # ── Disruption ───────────────────────────────────────────────────────
    {
        'id': 'V1.1', 'dim': 'disruption', 'depth': 1,
        'title': 'Every Subject Has a Default Photograph',
        'principle': 'Every subject has a default photograph. Yours should not be it.',
        'commons_file': 'File:Lange-MigrantMother02.jpg',
        'commons_caption': 'Migrant Mother · Dorothea Lange · 1936 · Public domain',
        'master': 'Dorothea Lange', 'master_quote': 'The camera is an instrument that teaches people how to see without a camera.',
        'assignments': {
            'Wildlife':     'Frame the animal on a third of the frame, leaving space in front of it to move or look into — never space behind it.',
            'Street':       'Photograph the street with no people in it. Make it about what they left behind.',
            'Nature':       'Shoot through something — grass, water, another plant. Let the obstruction become the frame.',
            'Landscape':    'Shoot the same location at flat noon light. Find what golden hour was hiding.',
            'People':       'Frame your subject off-centre, on a third of the frame, not in the middle. Use what is left in the other two-thirds — a wall, a shadow, a window — to say something about them.',
            'Documentary':  'Find the one person the event has not reached yet. That is your frame.',
            'Macro':        'Fill 80% of the frame with empty space — water, sky, blur, blank wall. Let the subject be small. Negative space is not absence, it\'s where the eye rests.',
            'Creative':     'Use your technique on a subject it was never intended for.',
            'Drone':        'Find a leading line from altitude — a road, a river, a fence line — and place it on a third of the frame, not through the centre.',
            'Wedding':      'Use a doorway, an arch, or a row of chairs to frame the couple naturally. Let the venue build the frame, not just your composition.',
            'Fashion':      'Place the model on a third of the frame. Use the empty two-thirds deliberately — it should feel intentional, not empty.',

            'Wildlife_mobile':      'Find a common subject — a pigeon, a crow, a dog — and photograph it as if it were rare. Change your angle, get to its eye level, find the moment when the ordinary reveals something unexpected. The disruption is not in the subject — it is in how you chose to look at it.',
            'Street_mobile':      "Find the most photographed spot near you — a monument, a view, a famous corner — and make the image nobody else is making. Shoot from ground level, from behind, through something, at the wrong time of day. The phone lets you get into positions a camera bag won't. Use that. The assignment is one image that no tourist is taking.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Find a landscape you can reach in 15 minutes. Photograph it from a position that requires effort — lying flat, climbing, crouching in water, shooting directly into the light. The phone's wide lens rewards extreme positions. Find the angle that changes what the place means.",
            'People_mobile':      'Photograph a person from behind, from the side, or in silhouette — never face-on. The disruption is removing the expectation of eye contact from a portrait. The image should communicate who the person is without showing their face.',
            'Documentary_mobile':      'Find a moment of ordinary life and photograph it from inside rather than outside. Stand in the crowd, not in front of it. The phone gives you cover. Use it to get to a position a camera would never reach unnoticed.',
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Use your phone's limitations as the creative tool. Shoot directly into a light source, move the phone during a long exposure (use night mode with movement), reflect your subject in a window or puddle, shoot through glass. The constraint is that you have no ND filter, no tripod thread, no remote — improvise around that.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph an ordinary household object from every angle except the obvious one.',
    },
    {
        'id': 'V1.2', 'dim': 'disruption', 'depth': 2,
        'title': 'Disruption That Serves the Subject',
        'principle': 'Disruption that serves the subject works. Disruption for its own sake does not.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Ernst Haas', 'master_quote': 'The camera doesn\'t make a bit of difference. All of them can record what you are seeing.',
        'assignments': {
            'Wildlife':     'Use a slow shutter on a moving subject deliberately. The blur must say something.',
            'Street':       'Find the angle where the subject becomes secondary to what surrounds them.',
            'Nature':       'Apply a technique that removes the subject\'s detail entirely. What remains?',
            'Landscape':    'Make an exposure decision that a camera in auto mode would refuse.',
            'People':       'Remove the face from the portrait. Make the body the entire statement.',
            'Documentary':  'Photograph the detail that stands for the event, not the event itself.',
            'Macro':        'Set your macro lens to maximum magnification and defocus deliberately — not slightly soft, fully blurred. Find the frame where colour and shape remain but the subject disappears. The image should be unidentifiable.',
            'Creative':     'Shoot until one frame is unrecognisable as its source.',
            'Drone':        'Fly at 10 metres. The disruption is proximity, not altitude.',
            'Wedding':      'Photograph the five seconds after the peak moment. Not during it.',
            'Fashion':      'Put the fashion in weather. Rain, wind, mud. The disruption is context.',

            'Wildlife_mobile':      'Find a common subject — a pigeon, a crow, a dog — and photograph it as if it were rare. Change your angle, get to its eye level, find the moment when the ordinary reveals something unexpected. The disruption is not in the subject — it is in how you chose to look at it.',
            'Street_mobile':      "Find the most photographed spot near you — a monument, a view, a famous corner — and make the image nobody else is making. Shoot from ground level, from behind, through something, at the wrong time of day. The phone lets you get into positions a camera bag won't. Use that. The assignment is one image that no tourist is taking.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Find a landscape you can reach in 15 minutes. Photograph it from a position that requires effort — lying flat, climbing, crouching in water, shooting directly into the light. The phone's wide lens rewards extreme positions. Find the angle that changes what the place means.",
            'People_mobile':      'Photograph a person from behind, from the side, or in silhouette — never face-on. The disruption is removing the expectation of eye contact from a portrait. The image should communicate who the person is without showing their face.',
            'Documentary_mobile':      'Find a moment of ordinary life and photograph it from inside rather than outside. Stand in the crowd, not in front of it. The phone gives you cover. Use it to get to a position a camera would never reach unnoticed.',
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Use your phone's limitations as the creative tool. Shoot directly into a light source, move the phone during a long exposure (use night mode with movement), reflect your subject in a window or puddle, shoot through glass. The constraint is that you have no ND filter, no tripod thread, no remote — improvise around that.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Make two frames of the same object — one conventional, one that shows something the first cannot.',
    },
    {
        'id': 'V1.3', 'dim': 'disruption', 'depth': 3,
        'title': 'The Most Disruptive Images Look Inevitable',
        'principle': 'The most disruptive images look inevitable in retrospect.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Daido Moriyama', 'master_quote': 'I want to express the feeling of reality that is beyond imagination.',
        'assignments': {
            'Wildlife':     'Fill most of the frame with negative space — sky, water, blur — and let the animal be small. Let the space say something about scale or solitude.',
            'Street':       'Spend thirty minutes finding the angle that feels inevitable, not just different.',
            'Nature':       'Ask of each frame: does this disruption reveal or merely decorate?',
            'Landscape':    'Process one image to match the emotional memory of being there, not the visual record.',
            'People':       'Make a portrait using minimalism — a plain wall, one colour, one light source. Remove everything that is not the person.',
            'Documentary':  'Find the detail that makes the viewer understand the whole story without seeing it.',
            'Macro':        'Make a macro image that the viewer cannot immediately identify. Then reveal the source.',
            'Creative':     'Apply your most familiar technique to a subject it was never designed for. Then make one frame where the technique disappears completely — the viewer sees only the subject. That is the standard.',
            'Drone':        'Fly over a location you know from the ground. Find one repeating pattern — a field, a road grid, a shoreline. Isolate it until nothing else is in the frame. The pattern is the entire image.',
            'Wedding':      'Find one wedding detail — the ring, a single flower, a folded program — and shoot it against negative space. Let it stand for the whole day.',
            'Fashion':      'Strip the frame down to the garment and empty space. No props, no background detail. Minimalism is the technique.',

            'Wildlife_mobile':      'Find a common subject — a pigeon, a crow, a dog — and photograph it as if it were rare. Change your angle, get to its eye level, find the moment when the ordinary reveals something unexpected. The disruption is not in the subject — it is in how you chose to look at it.',
            'Street_mobile':      "Find the most photographed spot near you — a monument, a view, a famous corner — and make the image nobody else is making. Shoot from ground level, from behind, through something, at the wrong time of day. The phone lets you get into positions a camera bag won't. Use that. The assignment is one image that no tourist is taking.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Find a landscape you can reach in 15 minutes. Photograph it from a position that requires effort — lying flat, climbing, crouching in water, shooting directly into the light. The phone's wide lens rewards extreme positions. Find the angle that changes what the place means.",
            'People_mobile':      'Photograph a person from behind, from the side, or in silhouette — never face-on. The disruption is removing the expectation of eye contact from a portrait. The image should communicate who the person is without showing their face.',
            'Documentary_mobile':      'Find a moment of ordinary life and photograph it from inside rather than outside. Stand in the crowd, not in front of it. The phone gives you cover. Use it to get to a position a camera would never reach unnoticed.',
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Use your phone's limitations as the creative tool. Shoot directly into a light source, move the phone during a long exposure (use night mode with movement), reflect your subject in a window or puddle, shoot through glass. The constraint is that you have no ND filter, no tripod thread, no remote — improvise around that.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Find the frame in your home that looks inevitable — the only way this corner could be photographed.',
    },
    # ── DM ───────────────────────────────────────────────────────────────
    {
        'id': 'M1.1', 'dim': 'dm', 'depth': 1,
        'title': 'Action and Geometry',
        'principle': 'The decisive moment is not the action. It is when the action and the geometry coincide.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Henri Cartier-Bresson', 'master_quote': 'To photograph is to hold one\'s breath when all faculties converge to capture fleeting reality.',
        'assignments': {
            'Wildlife':     'Pan with a moving or flying subject at a slow shutter speed — 1/30 to 1/60. The background blurs, the subject stays sharp. Geometry and motion control, together.',
            'Street':       'Find a background worth waiting for. Stand in front of it until someone walks through it correctly.',
            'Nature':       'Identify your timing window. Then identify your geometric window. Wait for both simultaneously.',
            'Landscape':    'Find a landscape with a moving element — cloud, tide, mist. Wait for it to land in the right position.',
            'People':       'Set your light first. Then wait for the expression to arrive into it.',
            'Documentary':  'Photograph the reaction, not the action. The decisive moment in documentary is often the response.',
            'Macro':        'Shoot only when the subject\'s eye is within your depth of field plane. Every other frame is a miss.',
            'Creative':     'Identify the single variable you cannot control. Wait for it to land correctly.',
            'Drone':        'Find a moving subject below — a vehicle, a boat, a herd — and follow it at constant altitude and distance. The geometry between subject and ground is your frame. Shoot a burst and find the one where both are right.',
            'Wedding':      'Identify your light and background first. Then wait for the emotional peak to arrive.',
            'Fashion':      'Shoot movement. Find the one frame where the cloth and the body are simultaneously right.',

            'Wildlife_mobile':      'Choose one subject and stay with it. Do not change position. Watch its behaviour and anticipate what it is about to do — lift its head, open its wings, turn toward the light. The moment is always one breath before the action peaks. Proximity is your only tool. Get as close as the subject allows and wait.',
            'Street_mobile':      'Find a busy spot — a crossing, a market entrance, a bus stop — and stand still. Watch what moves through the frame. Pre-compose on an empty or simple background. Wait for one person to walk into the right position and tap the shutter at the peak. You get ten minutes. One frame is the target.',
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      'Return to a location you know at a different time of day than you normally shoot. Pre-compose your frame before the light arrives. The decisive moment in landscape is the second the light hits exactly where you predicted. Wait for it. One frame. No cropping — the composition is set before you press.',
            'People_mobile':      "Spend ten minutes with one person doing something — cooking, reading, working, talking. Do not ask them to pose. Watch for the gesture or expression that is most true to what they're doing and photograph only that moment. The phone disappears when you're patient enough.",
            'Documentary_mobile':      "Find something happening and position yourself before it peaks — a queue forming, a transaction, a handshake, a departure. Compose with empty space in the direction the action will move. The moment is when all the elements align. Do not move the camera after you've composed. Wait.",
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Find a moving subject at home — person, pet, light shifting. Build the frame before the movement arrives.',
    },
    {
        'id': 'M1.2', 'dim': 'dm', 'depth': 2,
        'title': 'Anticipation Is Not Waiting',
        'principle': 'Anticipation is not waiting. It is reading the scene until you know where the moment will be.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Raghu Rai', 'master_quote': 'The camera is not a machine. It is an extension of your eye.',
        'assignments': {
            'Wildlife':     'Watch for ten minutes before shooting. Identify the behaviour pattern. Predict the next peak.',
            'Street':       'Spend five minutes in one spot without shooting. Read where the moment will happen. Then photograph it.',
            'Nature':       'Identify the element you cannot control. Read its rhythm. Time your frame to its cycle.',
            'Landscape':    'Arrive before the light. Identify where the light will land. Be in position when it does.',
            'People':       'Talk to your subject before photographing them. Learn their rhythm.',
            'Documentary':  'Read the event\'s structure. Identify what comes next. Be in position before it arrives.',
            'Macro':        'Time your subject\'s rhythm for five minutes before shooting.',
            'Creative':     'Test one frame. Read what the technique is doing. Adjust for the next with that knowledge.',
            'Drone':        'Before flying, identify every moving element and predict where it will be in sixty seconds.',
            'Wedding':      'Identify who in the crowd is about to feel something. Be ready.',
            'Fashion':      'Shoot between takes, not during them. The authentic moment arrives when the model forgets the camera.',

            'Wildlife_mobile':      'Choose one subject and stay with it. Do not change position. Watch its behaviour and anticipate what it is about to do — lift its head, open its wings, turn toward the light. The moment is always one breath before the action peaks. Proximity is your only tool. Get as close as the subject allows and wait.',
            'Street_mobile':      'Find a busy spot — a crossing, a market entrance, a bus stop — and stand still. Watch what moves through the frame. Pre-compose on an empty or simple background. Wait for one person to walk into the right position and tap the shutter at the peak. You get ten minutes. One frame is the target.',
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      'Return to a location you know at a different time of day than you normally shoot. Pre-compose your frame before the light arrives. The decisive moment in landscape is the second the light hits exactly where you predicted. Wait for it. One frame. No cropping — the composition is set before you press.',
            'People_mobile':      "Spend ten minutes with one person doing something — cooking, reading, working, talking. Do not ask them to pose. Watch for the gesture or expression that is most true to what they're doing and photograph only that moment. The phone disappears when you're patient enough.",
            'Documentary_mobile':      "Find something happening and position yourself before it peaks — a queue forming, a transaction, a handshake, a departure. Compose with empty space in the direction the action will move. The moment is when all the elements align. Do not move the camera after you've composed. Wait.",
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Watch someone at home for five minutes without photographing. Predict their next gesture. Photograph it.',
    },
    {
        'id': 'M1.3', 'dim': 'dm', 'depth': 3,
        'title': 'The Threshold Moment',
        'principle': 'Sometimes the decisive moment is the one just before the action — when anticipation itself is visible.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Henri Cartier-Bresson', 'master_quote': 'Your first 10,000 photographs are your worst.',
        'assignments': {
            'Wildlife':     'Make one frame before the action. The viewer should feel the action is inevitable.',
            'Street':       'Shoot one frame early — before the gesture resolves, before the person is fully in the light.',
            'Nature':       'Find a subject at the moment just before its transformation.',
            'Landscape':    'Make the frame at the moment of maximum anticipation — the tide still coming in, the sun not yet at the horizon, the mist still forming. Stop before the scene resolves into its obvious final state.',
            'People':       'Photograph the moment just before your subject does the thing you came to photograph.',
            'Documentary':  'Find the moment of maximum tension before release.',
            'Macro':        'Shoot the approach, not the arrival.',
            'Creative':     'Start exposing earlier than you normally would. The beginning of the technique is often more interesting.',
            'Drone':        'Anticipate the frame one beat early. The approach is the tension.',
            'Wedding':      'Find the five seconds before each peak moment. Photograph them instead of the peak.',
            'Fashion':      'Shoot the moment the model is still becoming the image, not after they have arrived.',

            'Wildlife_mobile':      'Choose one subject and stay with it. Do not change position. Watch its behaviour and anticipate what it is about to do — lift its head, open its wings, turn toward the light. The moment is always one breath before the action peaks. Proximity is your only tool. Get as close as the subject allows and wait.',
            'Street_mobile':      'Find a busy spot — a crossing, a market entrance, a bus stop — and stand still. Watch what moves through the frame. Pre-compose on an empty or simple background. Wait for one person to walk into the right position and tap the shutter at the peak. You get ten minutes. One frame is the target.',
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      'Return to a location you know at a different time of day than you normally shoot. Pre-compose your frame before the light arrives. The decisive moment in landscape is the second the light hits exactly where you predicted. Wait for it. One frame. No cropping — the composition is set before you press.',
            'People_mobile':      "Spend ten minutes with one person doing something — cooking, reading, working, talking. Do not ask them to pose. Watch for the gesture or expression that is most true to what they're doing and photograph only that moment. The phone disappears when you're patient enough.",
            'Documentary_mobile':      "Find something happening and position yourself before it peaks — a queue forming, a transaction, a handshake, a departure. Compose with empty space in the direction the action will move. The moment is when all the elements align. Do not move the camera after you've composed. Wait.",
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph someone at home in the moment before they do something — sitting down, opening a book, looking up.',
    },
    # ── Wonder ───────────────────────────────────────────────────────────
    {
        'id': 'W1.1', 'dim': 'wonder', 'depth': 1,
        'title': 'The Subject Is Not Rare. The Seeing Is.',
        'principle': 'The subject is not rare. The seeing is.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Vivian Maier', 'master_quote': 'Taking pictures is savoring life intensely, every hundredth of a second.',
        'assignments': {
            'Wildlife':     'Photograph a species you consider ordinary. Make the frame that proves it is not.',
            'Street':       'Walk slowly. Stop every time something almost catches your eye. Look at what almost caught it.',
            'Nature':       'Find a plant or natural object you walk past regularly. Make the frame that reveals what is actually there.',
            'Landscape':    'Shoot the landscape with a telephoto. Find the fragment that holds the whole.',
            'People':       'Photograph someone doing something ordinary. Find the instant of involuntary truth.',
            'Documentary':  'Find the single object in the scene that, photographed alone, makes the viewer understand everything.',
            'Macro':        'Choose the most ordinary subject you can find. Photograph it at maximum magnification.',
            'Creative':     'Apply your technique to something completely mundane. Does it reveal something, or only decorate?',
            'Drone':        'Fly over a location you know from the ground. Find what the ground perspective has always hidden.',
            'Wedding':      'Stop photographing the scheduled moments. Photograph only what happens between them.',
            'Fashion':      'Put the camera down during the planned shoot. Pick it up only when something unplanned happens.',

            'Wildlife_mobile':      'Find a foreground element — a branch, reeds, a blade of grass — and let it partially overlap your subject. Move until the foreground and subject sit in the same plane of interest. Proximity does what telephoto cannot: it forces the relationship between near and far. One frame only.',
            'Street_mobile':      'Walk your neighbourhood with your phone only. Find a natural frame — a doorway, an arch, a gap between two people, a window — and position yourself so your subject sits inside it. You cannot zoom — move until the composition resolves. The frame must be visible without cropping.',
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Find a foreground object — a rock, a plant, a fence post — within arm's reach and crouch low so it anchors the frame. The phone's wide lens makes foregrounds large and backgrounds recede — use that. The foreground must earn its place: it should add depth, not distract.",
            'People_mobile':      "Find a person and position yourself so something in the environment frames them — a doorway, a pool of light, a shadow. You are not photographing the person. You are photographing the relationship between the person and their context. Get close. The phone is invisible when you're curious, not predatory.",
            'Documentary_mobile':      'Find a moment happening inside a space — a market, a street, a room — and let the space frame the moment rather than filling the frame with the subject. The phone gives you access. Use it: get inside the scene, not in front of it.',
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Walk your home slowly. Find one thing you have never photographed. Make the frame that reveals it.',
    },
    {
        'id': 'W1.2', 'dim': 'wonder', 'depth': 2,
        'title': 'Access Is Earned Before the Camera Is Raised',
        'principle': 'Access wonder is earned before the camera is raised.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Sebastião Salgado', 'master_quote': 'Photography is not for me an end in itself, but it is a medium for me to tell a story.',
        'assignments': {
            'Wildlife':     'Spend the first 30 minutes at the location only watching — no camera raised. Photograph only what that patience reveals.',
            'Street':       'Stand in one street location for at least an hour before you raise the camera. Photograph only what that presence earns you, not the first thing you saw.',
            'Nature':       'Go somewhere that requires effort to reach. The access is the difficulty and the wonder.',
            'Landscape':    'Find a landscape location not on any photography website. The unknown location is the access.',
            'People':       'Spend real time talking with someone before you ask to photograph them. Earn it in the same sitting, not with a single transactional ask.',
            'Documentary':  'Find a story that requires an introduction to access. Get the introduction before raising the camera.',
            'Macro':        'Find a macro subject that requires permission or relationship to photograph.',
            'Creative':     'Build something for the photograph. The construction is the access.',
            'Drone':        'Fly somewhere that requires permission. The bureaucratic difficulty is part of the work.',
            'Wedding':      'If photographing someone you just met, spend an hour with them before the session begins.',
            'Fashion':      'Find a fashion location that requires negotiation. The negotiation is part of the creative work.',

            'Wildlife_mobile':      'Find a foreground element — a branch, reeds, a blade of grass — and let it partially overlap your subject. Move until the foreground and subject sit in the same plane of interest. Proximity does what telephoto cannot: it forces the relationship between near and far. One frame only.',
            'Street_mobile':      'Walk your neighbourhood with your phone only. Find a natural frame — a doorway, an arch, a gap between two people, a window — and position yourself so your subject sits inside it. You cannot zoom — move until the composition resolves. The frame must be visible without cropping.',
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Find a foreground object — a rock, a plant, a fence post — within arm's reach and crouch low so it anchors the frame. The phone's wide lens makes foregrounds large and backgrounds recede — use that. The foreground must earn its place: it should add depth, not distract.",
            'People_mobile':      "Find a person and position yourself so something in the environment frames them — a doorway, a pool of light, a shadow. You are not photographing the person. You are photographing the relationship between the person and their context. Get close. The phone is invisible when you're curious, not predatory.",
            'Documentary_mobile':      'Find a moment happening inside a space — a market, a street, a room — and let the space frame the moment rather than filling the frame with the subject. The phone gives you access. Use it: get inside the scene, not in front of it.',
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph a family member or housemate doing something private — reading, cooking, thinking. Ask first.',
    },
    {
        'id': 'W1.3', 'dim': 'wonder', 'depth': 3,
        'title': 'Emotional Wonder Cannot Be Planned',
        'principle': 'Emotional wonder cannot be planned — but it can be prepared for.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Sebastião Salgado', 'master_quote': 'I hope that the person who visits my exhibitions, who buys my book, feels what I felt.',
        'assignments': {
            'Wildlife':     'Stay with one subject long enough that its behaviour becomes predictable. Wait for the moment that breaks the pattern.',
            'Street':       'Spend two hours in one location. Photograph only in the second hour.',
            'Nature':       'Visit one natural location at a different time of day than you normally would — dawn instead of midday, dusk instead of morning. Find the light that produces the emotion you want.',
            'Landscape':    'Before shooting, name the emotion you want the image to produce. Every decision serves that feeling.',
            'People':       'Photograph for longer than feels necessary. The emotional truth arrives after the subject has exhausted their performance.',
            'Documentary':  'Find the one person whose face contains the entire emotional weight of the event.',
            'Macro':        'Name the emotion your macro subject produces before you shoot.',
            'Creative':     'Show your work to someone unfamiliar with photography. Ask what they feel, not what they think.',
            'Drone':        'Find the altitude where human scale disappears and pattern takes over.',
            'Wedding':      'Find the emotion this particular wedding contains that no other wedding has. Photograph that.',
            'Fashion':      'Strip back until the fashion disappears and the person remains.',

            'Wildlife_mobile':      'Find a foreground element — a branch, reeds, a blade of grass — and let it partially overlap your subject. Move until the foreground and subject sit in the same plane of interest. Proximity does what telephoto cannot: it forces the relationship between near and far. One frame only.',
            'Street_mobile':      'Walk your neighbourhood with your phone only. Find a natural frame — a doorway, an arch, a gap between two people, a window — and position yourself so your subject sits inside it. You cannot zoom — move until the composition resolves. The frame must be visible without cropping.',
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Find a foreground object — a rock, a plant, a fence post — within arm's reach and crouch low so it anchors the frame. The phone's wide lens makes foregrounds large and backgrounds recede — use that. The foreground must earn its place: it should add depth, not distract.",
            'People_mobile':      "Find a person and position yourself so something in the environment frames them — a doorway, a pool of light, a shadow. You are not photographing the person. You are photographing the relationship between the person and their context. Get close. The phone is invisible when you're curious, not predatory.",
            'Documentary_mobile':      'Find a moment happening inside a space — a market, a street, a room — and let the space frame the moment rather than filling the frame with the subject. The phone gives you access. Use it: get inside the scene, not in front of it.',
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph one person at home for thirty minutes without directing them. Wait for the moment of unguarded truth.',
    },
    # ── AQ ───────────────────────────────────────────────────────────────
    {
        'id': 'A1.1', 'dim': 'aq', 'depth': 1,
        'title': 'Name What the Image Makes the Viewer Feel',
        'principle': '"Powerful" is not an emotion. Name what the image makes the viewer feel.',
        'commons_file': 'File:Lange-MigrantMother02.jpg',
        'commons_caption': 'Migrant Mother · Dorothea Lange · 1936 · The emotion is exhausted dignity. Public domain',
        'master': 'Dorothea Lange', 'master_quote': 'A camera is a tool for learning how to see without a camera.',
        'assignments': {
            'Wildlife':     'Before shooting, choose one word: awe, fragility, power, strangeness. Make only frames that deliver that feeling.',
            'Street':       'Walk looking for one of these: loneliness, defiance, dignity, connection. Do not raise the camera until you see it.',
            'Nature':       'Find a natural subject and name the emotion it produces. Find the frame that maximises that specific feeling.',
            'Landscape':    'Stand in the landscape before shooting. Name the emotion. Make the frame that delivers it.',
            'People':       'Identify the emotion of your subject before you raise the camera. Expose for that feeling.',
            'Documentary':  'Name the emotion the story produces. Find the frame that makes it undeniable.',
            'Macro':        'Choose the emotion your macro subject produces. Find the angle that delivers it most precisely.',
            'Creative':     'Name the feeling before applying the technique. The technique serves the feeling.',
            'Drone':        'Find the altitude where the emotion you want becomes available.',
            'Wedding':      'Identify the specific emotional register of this couple. Every frame serves that register.',
            'Fashion':      'Name the emotional register the garment demands. Direct toward that feeling, not conventional beauty.',

            'Wildlife_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Street_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'People_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Documentary_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph one room in your home. Name the emotion before you shoot. Make three frames that deliver it.',
    },
    {
        'id': 'A1.2', 'dim': 'aq', 'depth': 2,
        'title': 'Light Is the Instrument of Emotion',
        'principle': 'Light is the instrument of emotion — not the subject.',
        'commons_file': None,
        'commons_caption': None,
        'master': 'Yousuf Karsh', 'master_quote': 'Look and think before opening the shutter. The heart and mind are the true lens of the camera.',
        'assignments': {
            'Wildlife':     'Find your subject when the light is low and behind them — dawn or dusk. Shoot the rim of light on fur or feathers. Then move so the light is beside them and find the catchlight in the eye. Two frames, two different emotions. One light, two readings.',
            'Street':       'Shoot in black and white. Find a scene where the light is already doing the work. Stand in it. Wait for the subject to arrive.',
            'Nature':       'Shoot one natural subject in black and white at three different times of day. Which light produces the emotion you want?',
            'Landscape':    'Shoot in black and white and remove all post-processing from one landscape image. What emotion does the original light produce on its own?',
            'People':       'Photograph the same person in backlight and side light, in black and white. Backlight makes a portrait soft and atmospheric; side light reveals texture and character. Pick the one that\'s honest about who they are.',
            'Documentary':  'Shoot in black and white. Do not modify the light. Use the light the scene already has. Its quality is the story.',
            'Macro':        'Shoot one macro subject in black and white, with light from three different directions. Texture and form are all that is left to work with.',
            'Creative':     'Make the same technique image in black and white, in two different light conditions. The light alone determines which one has a feeling.',
            'Drone':        'Fly the same location in black and white — side-lit by low sun, then directly into it for backlight. Side light reveals texture in land; backlight flattens it into shape.',
            'Wedding':      'Shoot one frame of the couple in hard backlight and one in soft side light, both in black and white. Compare which one protects the emotion of the moment.',
            'Fashion':      'Shoot in black and white. Use only backlight or only side light for the entire shoot — no fill, no reflector. Commit to what the direction does to the garment.',

            'Wildlife_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Street_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'People_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Documentary_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph the same corner of your home in morning light and evening light, in black and white. Name the different emotions.',
    },
    {
        'id': 'A1.3', 'dim': 'aq', 'depth': 3,
        'title': 'The Unexpected Emotion',
        'principle': 'The image that makes the viewer feel something they did not expect to feel is the one they remember.',
        'commons_file': None,
        'commons_caption': None,
        'master': None, 'master_quote': None,
        'assignments': {
            'Wildlife':     'Find the moment a predator or dominant animal is still, resting, or grooming — the frame that shows its life between hunts. Most wildlife photography shows power or action. Find the frame that shows the animal simply existing.',
            'Street':       'Find the thing on the street that is quiet, still, or tender — the opposite of the decisive moment. A sleeping figure, an empty bench, a single flower. Street photography is not always about action.',
            'Nature':       'Find the emotion in a natural subject that nature photography never names.',
            'Landscape':    'Find the emotion the landscape produces that a landscape photograph is not supposed to produce.',
            'People':       'Find the emotional contradiction your subject contains. Photograph the one people photography does not usually show.',
            'Documentary':  'Find the moment of unexpected emotional register — hope inside despair, dignity inside hardship.',
            'Macro':        'Find the macro subject that produces an emotion its scale should not produce.',
            'Creative':     'Make a technique image that produces a specific named emotion in a viewer who does not know the technique.',
            'Drone':        'Find the drone frame where a human element produces an unexpected emotion against the abstract scale.',
            'Wedding':      'Find the one moment where the emotional register is the opposite of what the event is supposed to feel.',
            'Fashion':      'Strip the fashion image of everything that makes it fashion. What emotion does the person produce?',

            'Wildlife_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Street_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Nature_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Landscape_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'People_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Documentary_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Macro_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Creative_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Drone_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Wedding_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
            'Fashion_mobile':      "Photograph something that makes you feel a specific emotion — not 'beautiful' or 'interesting', but one named feeling: lonely, joyful, uneasy, tender. Before you press the shutter, name the emotion out loud. Then make the image that delivers it to a stranger who knows nothing about where you were.",
        },
        'indoor_assignment': 'Photograph your home in a way that produces the emotion it is not supposed to produce — warmth as unease, comfort as loneliness.',
    },
]

# Index for fast lookup by ID
_CURRICULUM_BY_ID = {p['id']: p for p in _CURRICULUM}
